### PR TITLE
correct cookie module link, actually uses cookies

### PR DESCRIPTION
**Pull request by tjmehta**
updated node module cookies reference to be the correct repo "cookies".. not "cookie"

Thanks

### CODE REVIEW

**Comment by DaAwesomeP** [comment]
I forked this from the original repo and I'm now not sure where this is coming from. There is no `cookies` or `cookie` dependency in `package.json`. I don't think that it's used at all. Do you think that it is coming from a different package in Koa?

**Comment by DaAwesomeP** [comment]
@tjmehta Do you think that I should remove the cookies section entirely? I'm not sure where this library is used.

**Comment by DaAwesomeP** [comment]
@tjmehta any updates?

**Comment by tjmehta** [comment]
I believe you are right it uses koa's built in cookie api, which uses "cookies" http://koajs.com/#ctx-cookies-set-name-value-options-

You can probably just remove the entire section

**Comment by DaAwesomeP** [comment]
@tjmehta OK, I will. Closing this.

**Pull request closed without merging**
